version: '3.7'

services:
  web:
    container_name: website
    build: packages/client
    image: website
    expose:
      - '80'
  proxy:
    image: nginx:alpine
    container_name: proxy_service
    volumes:
      - './proxy.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
